steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - helloraghav
  - --source=.
  - --trigger-http
  - --runtime=python37
  --set-env-vars FOO:bar,BAZ:boo

env:
  - 'FOO=us-bar'
  - 'BAZ=boo'
