steps:
- name: 'gcr.io/cloud-builders/gcloud'

  
  ## Working args: ['functions','deploy','helloraghav','--source=.','--trigger-http','--runtime=python37','--update-env-vars=db_name=cars,db_user=postgres,db_pass=XXXXXXXXXX ']
  ## Working args: ['functions','deploy','helloraghav','--source=.','--trigger-http','--runtime=python37','--update-env-vars=db_name=cars,db_user=postgres,db_pass=XXXXXXXXXX ','--project=manifest-truth-270909']
  args: ['functions','deploy','helloraghav','--source=./carsub_address','--trigger-http','--runtime=python37','--update-env-vars=db_name=cars,db_user=postgres,db_pass=XXXXXXXXXX ','--timeout=540s',--project=manifest-truth-270909']
  
  540 seconds
  
  #--update-env-vars=db_name="cars",db_user="postgres",db_pass="NKumoLjjOIiJOBIz"]
 
#  ,cloud_sql_connection_name=aaa-a3labs-carsubdev:us-central1:aaa-a3labs-carsubdev]] '--clear-env-vars',


#--substitutions=_NODE_VERSION_1="v6.9.4",_NODE_VERSION_2="v6.9.5" 
